# -*- coding: utf-8 -*-
# Part of Vertel. See LICENSE file for full copyright and licensing details.

import logging

from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

_logger = logging.getLogger(__name__)


class RolloutModuleLine(models.Model):
    """An instance of a content type — "CRM kap 3", "Veckans enkät v.41".

    For a static type this is created once and waits until done. For a
    periodic type a cron creates a new line each period.
    """

    _name = 'rollout.module.line'
    _description = 'Rollout App Module Line'
    _order = 'sequence, name'

    name = fields.Char('Name', required=True, translate=True)
    module_id = fields.Many2one(
        'rollout.module', string='Type', required=True, ondelete='cascade')
    sequence = fields.Integer('Sequence', default=10)
    active = fields.Boolean('Active', default=True)

    module_rel = fields.Reference(
        selection='_selection_module_rel', string='Content',
        help="The record this line points at, e.g. a course or a survey.")

    # -- Values, inherited from the type unless overridden --
    points = fields.Integer('Points')
    coins = fields.Integer('Coins')
    badge_id = fields.Many2one(
        'gamification.badge', string='Badge',
        help="Displayed as the line's reward. The badge itself is awarded "
             "by gamification, never by this module.")

    # -- State --
    state = fields.Selection([
        ('locked', 'Locked'),
        ('open', 'Open'),
        ('done', 'Done'),
    ], string='Status', default='open', required=True,
        help="Line-level state, used only for lines concluded for everyone. "
             "Per-person lock and completion live on rollout.app.line.")

    # -- Period --
    period_start = fields.Date('Period Start')
    period_end = fields.Date('Period End')
    publish_at = fields.Datetime(
        'Publish At', help="When the line becomes visible in the app.")
    remind_at = fields.Datetime(
        'Remind At', help="When a reminder is evaluated if still open.")

    # -- Achievement gating --
    source_line_id = fields.Many2one(
        'rollout.module.line', string='Unlocked By',
        help="The line whose completion unlocks this one.")
    unlock_badge_id = fields.Many2one(
        'gamification.badge', string='Unlock Badge',
        help="The badge that unlocks this line.")

    app_line_ids = fields.One2many(
        'rollout.app.line', 'module_line_id', string='Participant Lines')
    app_line_count = fields.Integer(
        'Participants', compute='_compute_app_line_count')

    _sql_constraints = [
        ('points_non_negative', 'CHECK(points >= 0)',
         'Points cannot be negative.'),
        ('coins_non_negative', 'CHECK(coins >= 0)',
         'Coins cannot be negative.'),
    ]

    @api.model
    def _selection_module_rel(self):
        """Models a line may reference.

        Open by default: the type's ``allowed_model`` is the real gate. This
        lists every installed model so the Reference field accepts them.
        """
        return [
            (model.model, model.name)
            for model in self.env['ir.model'].sudo().search([])
        ]

    @api.depends('app_line_ids')
    def _compute_app_line_count(self):
        for line in self:
            line.app_line_count = len(line.app_line_ids)

    @api.onchange('module_id')
    def _onchange_module_id(self):
        """Inherit the type's defaults when the module is chosen."""
        for line in self:
            if line.module_id:
                if not line.points:
                    line.points = line.module_id.default_points
                if not line.coins:
                    line.coins = line.module_id.default_coins

    @api.model_create_multi
    def create(self, vals_list):
        """Inherit points and coins from the type when not given."""
        for vals in vals_list:
            module = self.env['rollout.module'].browse(vals.get('module_id'))
            if module:
                if 'points' not in vals:
                    vals['points'] = module.default_points
                if 'coins' not in vals:
                    vals['coins'] = module.default_coins
        lines = super().create(vals_list)

        # A static line is available immediately, so generate participant
        # lines at once. Periodic lines are generated by the spawn cron.
        for line in lines:
            if line.module_id.spawn_mode == 'static':
                self._generate_app_lines(line)
        return lines

    @api.constrains('module_rel', 'module_id')
    def _check_module_rel_allowed(self):
        """A line may only reference a model its type permits.

        This is what makes the type a contract: a "Course" type can only
        point at a course.
        """
        for line in self:
            if not line.module_rel or not line.module_id:
                continue
            allowed = line.module_id.allowed_model
            if not allowed:
                continue
            referenced = line.module_rel._name
            if referenced != allowed:
                raise ValidationError(_(
                    "The type '%(type)s' only permits '%(allowed)s', but this "
                    "line references '%(referenced)s'.",
                    type=line.module_id.name,
                    allowed=allowed,
                    referenced=referenced,
                ))

    @api.constrains('period_start', 'period_end')
    def _check_period(self):
        """The period must be coherent."""
        for line in self:
            if line.period_start and line.period_end:
                if line.period_end < line.period_start:
                    raise ValidationError(_(
                        "The period end cannot be before the period start."))

    # ------------------------------------------------------------------
    # Generation and period lifecycle
    # ------------------------------------------------------------------
    @api.model
    def _generate_app_lines(self, line, users=None):
        """Create participant lines for a line, idempotently.

        Called when a static line is created, when a periodic line is
        spawned, and when a member joins. Re-running creates no duplicates.
        """
        AppLine = self.env['rollout.app.line']
        apps = self.env['rollout.app'].search([
            ('module_ids', 'in', line.module_id.id)])

        created = AppLine
        for app in apps:
            members = users if users is not None else app.project_id.team_member_ids
            for user in members:
                if user not in app.project_id.team_member_ids:
                    continue
                existing = AppLine.search([
                    ('app_id', '=', app.id),
                    ('module_line_id', '=', line.id),
                    ('user_id', '=', user.id),
                ], limit=1)
                if existing:
                    continue
                created |= AppLine.create({
                    'app_id': app.id,
                    'module_line_id': line.id,
                    'user_id': user.id,
                    # A line created locked stays locked per person until
                    # gamification unlocks it.
                    'locked': line.state == 'locked',
                })
        return created

    @api.model
    def _next_period_start(self, recurrence, after=None):
        """The first day of the next period."""
        after = after or fields.Date.today()
        if recurrence == 'daily':
            return after + relativedelta(days=1)
        if recurrence == 'weekly':
            # Next Monday.
            return after + relativedelta(days=7 - after.weekday())
        if recurrence == 'monthly':
            return (after + relativedelta(months=1)).replace(day=1)
        return None

    @api.model
    def _period_bounds(self, recurrence, start):
        """The end of a period that begins on ``start``."""
        if recurrence == 'daily':
            return start
        if recurrence == 'weekly':
            return start + relativedelta(days=6)
        if recurrence == 'monthly':
            return start + relativedelta(months=1, days=-1)
        return start

    @api.model
    def cron_rollout_app_spawn(self):
        """Spawn the next period's lines for periodic types.

        Idempotent per ``(module_id, period_start)``: a second run in the
        same period creates nothing.
        """
        today = fields.Date.today()
        modules = self.env['rollout.module'].search([
            ('spawn_mode', '=', 'periodic'),
            ('active', '=', True),
            ('recurrence', '!=', 'none'),
        ])

        spawned = self
        for module in modules:
            # Create as many periods ahead as the lead time asks for.
            for offset in range(1, (module.lead_time or 1) + 1):
                start = today
                for _ in range(offset):
                    start = self._next_period_start(module.recurrence, start)
                if not start:
                    continue

                existing = self.search([
                    ('module_id', '=', module.id),
                    ('period_start', '=', start),
                ], limit=1)
                if existing:
                    continue

                end = self._period_bounds(module.recurrence, start)
                # Publish at 07:00 on the first day of the period, remind
                # three days later.
                publish_at = fields.Datetime.to_datetime(f'{start} 07:00:00')
                remind_at = fields.Datetime.to_datetime(
                    f'{start + relativedelta(days=3)} 07:00:00')

                line = self.create({
                    'name': f'{module.name} {start.isoformat()}',
                    'module_id': module.id,
                    'state': 'open',
                    'period_start': start,
                    'period_end': end,
                    'publish_at': publish_at,
                    'remind_at': remind_at,
                    'points': module.default_points,
                    'coins': module.default_coins,
                })
                spawned |= line
                self._generate_app_lines(line)
                line._trigger_period_published()

        if spawned:
            _logger.info("rollout_app: spawned %s period lines", len(spawned))
        return spawned

    def _trigger_period_published(self):
        """Evaluate the 'period_published' nudge for the team."""
        self.ensure_one()
        apps = self.env['rollout.app'].search([
            ('module_ids', 'in', self.module_id.id)])
        for app in apps:
            for user in app.project_id.team_member_ids:
                self._fire_nudge('period_published', user, {
                    'period': self.period_start.isoformat(),
                    'line': self.name,
                })

    def _fire_nudge(self, event, user, context):
        """Fire every active nudge matching this event, for this user."""
        nudges = self.env['rollout.nudge'].search([
            ('trigger_event', '=', event),
            ('active', '=', True),
        ])
        for nudge in nudges:
            nudge.trigger(event, user, context)
